apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{cookiecutter.app_name}}
  name: {{cookiecutter.app_name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{cookiecutter.app_name}}
  template:
    metadata:
      labels:
        app: {{cookiecutter.app_name}}
    spec:
      containers:
        - image: 'cremerfc/appdirect:10'
          name: appdirect
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.app_name}}-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: {{cookiecutter.app_name}}
  type: LoadBalancer
