apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-direct
  name: app-direct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-direct
  template:
    metadata:
      labels:
        app: app-direct
    spec:
      containers:
        - image: 'cremerfc/appdirect:10'
          name: appdirect
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-direct-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: app-direct
  type: LoadBalancer
